version: '3'
services:
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smh
      MYSQL_USER: smh
      MYSQL_PASSWORD: smh
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/dump.sql:/docker-entrypoint-initdb.d/init.sql:ro
    expose:
      - 3306
    ports:
      - "3306:3306"
  smh:
    image: smh:latest
    restart: always
    depends_on:
      - database
    ports:
      - 8000:8000
volumes:
  mysql-data: